### PR TITLE
Added sunspires to unicorn calculator

### PR DESCRIPTION
**Pull request by Quizer85**
Looks like there's at least one more building... This should add the Sunspire to the unicorn calculator.

### CODE REVIEW

**Comment by Quizer85** [comment]
Please test that this works for you. The first time, it didn't take and just spat out NaN for all the prices, but after I did everything over, it seems to work now.

**Review by VariableVixen — APPROVED** [review]
Looks like it'll work nicely, conforms to the contribution guidelines. Nice work!

**Comment by Quizer85** [comment]
Ah, I totally forgot about those. Read a notification about them now existing a while ago, couldn't find them, promptly forgot about it.

But I read them just now. So I should in the future edit the src.js file and then make a pull request for that one? Also, where and how do I run `eslint --fix` ?

**Comment by VariableVixen** [comment]
...only just realised that you _didn't_ edit the source file (don't merge when you're tired, kids...) but yeah - any changes to `AutoKittens.js` are overwritten and lost on build. The `AutoKittens.src.js` file is the one to edit. I'll just... go move those over.

If you don't have a dev environment (at least a command line and the ability to use it) then you won't be able to; you have to install NodeJS and then from there you can install `eslint` via `npm`.

**Pull request merged**
